kind: pipeline
type: docker
name: default

trigger:
  branch:
  - main

steps:
# - name: Build & Test
#   image: rust:1.70
#   commands:
#     - cargo build
#     - cargo test --all
#     - cargo clean
    
- name: Build Container
  image: plugins/docker
  settings:
    platform: linux/amd64
    repo: pantry-manager-api/pantry-manager-api
    tags: 
    - latest
    dockerfile: ./dockerfile
    insecure: true
    registry: gitea.mjy-home.duckdns.org
    username:
      from_secret: username
    password:
      from_secret: password

# - name: Build Container
#   image: alpine:3.8
#   command:
#   - docker login gitea.example.com