kind: pipeline
type: docker
name: default

steps:
- name: Build & Test
  image: rust:1.70
  commands:
    - cargo build
    - cargo test --all
    - cargo clean

- name: Build Container
  image: plugins/docker
  settings:
    platform: linux/amd64
    repo: pantry-manager-api/pantry-manager-api
    tags: 
    - pantry-manager-api
    dockerfile: ./dockerfile
    registry: https://gitea.mjy-home.duckdns.org/

trigger:
  branch:
  - main