kind: pipeline
type: docker
name: amd64

platform:
  arch: amd64

steps:
  - name: 'build and test'
    image: rust:1.70
    commands:
      - cargo build
      - cargo test --all
      - cargo clean

  - name: 'items for sonar'
    image: rust:1.70
    commands:
      - cargo clippy --message-format=json
      - cargo clippy --message-format=json &> ./report.json

  - name: test
    image: alpine
    commands:
      - ls
      - cat report.json

  - name: 'code analysis'
    image: aosapps/drone-sonar-plugin
    settings:
      sonar_host:
        from_secret: sonar_host
      sonar_token:
        from_secret: sonar_token
      showProfiling: true
      usingProperties: true

  - name: Build & Deploy Linux Container
    image: plugins/docker
    settings:
      platform: linux/amd64
      repo: gitea.mjy-home.duckdns.org/michaelyahner/pantry-manager-api
      tags:
        - "latest-linux-amd64"
        - "0.1-linux-amd64"
      dockerfile: ./dockerfile
      registry: gitea.mjy-home.duckdns.org
      username:
        from_secret: username
      password:
        from_secret: password

---
kind: pipeline
type: docker
name: arm

platform:
  arch: arm64

depends_on:
  - amd64

steps:
  - name: Build & Deploy Arm Container
    image: plugins/docker
    settings:
      platform: linux/arm64
      repo: gitea.mjy-home.duckdns.org/michaelyahner/pantry-manager-api
      tags:
        - "latest-linux-arm64"
        - "0.1-linux-arm64"
      dockerfile: ./dockerfile
      registry: gitea.mjy-home.duckdns.org
      username:
        from_secret: username
      password:
        from_secret: password
