kind: pipeline
type: docker
name: default

steps:
- name: Build & Test
  image: rust:1.70
  commands:
    - cargo build
    - cargo test --all

- name: Build Container
  image: plugins/docker
  settings:
    platform: linux/amd64
    repo: pantrymanager/pantrymanagerapi
    dry_run: true
    tags: [pantry-manager-api]
    dockerfile: ./dockerfile

trigger:
  branch:
  - main