kind: pipeline
type: docker
name: default

steps:
- name: Build & Test
  image: rust:1.70
  commands:
    - cargo build
    - cargo test --all
    - cargo clean

- name: build
  image: alpine
  environment:
    USERNAME:
      from_secret: username
    PASSWORD:
      from_secret: password
  commands:
    - echo "You can call the secrets like this examples below."
    - echo $USERNAME
    - echo $PASSWORD
    - echo "In both cases, and for security reasons, you will see asteriks '*******' instead the value under the echo command."

- name: Build Container
  image: plugins/docker
  environment:
    USERNAME:
      from_secret: username
    PASSWORD:
      from_secret: password
  settings:
    platform: linux/amd64
    repo: pantry-manager-api/pantry-manager-api
    tags: 
    - pantry-manager-api
    dockerfile: ./dockerfile
    registry: gitea.mjy-home.duckdns.org/
    username: $USERNAME
    password: $PASSWORD

trigger:
  branch:
  - main