kind: pipeline
type: docker
name: default

trigger:
  branch:
    - main

steps:
  - name: Build & Test
    image: rust:1.70
    commands:
      - cargo build
      - cargo test --all
      - cargo clean

  - name: code-analysis
    image: aosapps/drone-sonar-plugin
    settings:
      sonar_host:
        from_secret: sonar_host
      sonar_token:
        from_secret: sonar_token

  - name: Build & Deploy Linux Container
    image: plugins/docker
    settings:
      platform: linux/amd64
      repo: gitea.mjy-home.duckdns.org/michael/pantry-manager-api
      tags:
        - "latest-linux-amd64"
        - "0.1-linux-amd64"
      dockerfile: ./dockerfile
      registry: gitea.mjy-home.duckdns.org
      username:
        from_secret: username
      password:
        from_secret: password

  - name: Build & Deploy Arm Container
    image: plugins/docker
    settings:
      platform: linux/arm64
      repo: gitea.mjy-home.duckdns.org/michael/pantry-manager-api
      tags:
        - "latest-linux-arm64"
        - "0.1-linux-arm64"
      dockerfile: ./dockerfile
      registry: gitea.mjy-home.duckdns.org
      username:
        from_secret: username
      password:
        from_secret: password
