//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "grocery")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub quantity: Option<i32>,
    pub shopped: Option<bool>,
    pub standard_quantity: Option<i32>,
    pub inventory_item_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::inventory::Entity",
        from = "Column::InventoryItemId",
        to = "super::inventory::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Inventory,
}

impl Related<super::inventory::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Inventory.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
