//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

pub use super::inventory::Entity as Inventory;
pub use super::products::Entity as Products;
pub use super::seaql_migrations::Entity as SeaqlMigrations;
